version: '3'

services:
  clean-node-api:
    image: mongo
    container_name: clean-node-api
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./_data/clean-node-api:/data/db
